# Generated by Django 5.2.6 on 2025-09-11 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.TextField(verbose_name='Название источника')),
                ('source_type', models.CharField(max_length=255, verbose_name='Вид источника: фильм, книга и тп')),
                ('author', models.CharField(max_length=255, verbose_name='Автор источника')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('text', models.TextField(unique=True, verbose_name='Цитата')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Вес (влияет на частоту показа)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Дизлайки')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('likes__gte', 0)), name='likes_gte0'), models.CheckConstraint(condition=models.Q(('dislikes__gte', 0)), name='dislikes_gte0'), models.CheckConstraint(condition=models.Q(('views__gte', 0)), name='views_gte0')],
            },
        ),
    ]
