# Generated by Django 5.2.6 on 2025-09-11 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Вид источника: фильм, книга и тп')),
            ],
            options={
                'verbose_name': 'Вид источника',
                'verbose_name_plural': 'Виды источников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('name', 'source_type')},
        ),
        migrations.RemoveField(
            model_name='source',
            name='author',
        ),
    ]
