# Generated by Django 5.2.6 on 2025-09-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sourcetype_alter_source_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sourcetype', verbose_name='Вид источника: фильм, книга и тп'),
        ),
    ]
